In [2]:
import numpy as np

In [3]:

array=np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
array1= np.random.randint(20,size=(3,3))
array1

array([[ 7,  9, 16],
       [ 3,  2, 10],
       [11,  7,  9]])

In [5]:
array2=np.ones((2,3,4))
print(array2)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [6]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])

c=np.add(a,b)
print(c)

[ 3  5  7  9 11]


In [7]:
 arr1=np.array([[1,3,4],[2,3,4]])
arr2=np.array([[2,3,4],[1,5,6]])

product=arr1 * arr2
print(product)

[[ 2  9 16]
 [ 2 15 24]]


In [8]:
 mat1=np.array([[1,2],[2,5]])
mat2=np.array([[6,5],[2,3]])
result=np.dot(mat1,mat2)
print(result)

[[10 11]
 [22 25]]


In [9]:
array3=np.arange(10)
r1=np.mean(array3)
print("mean",r1)

r2=np.std(array3)
print("Standard Deviation: ",r2)

r3=np.median(array3)
print("Median: ",r3)


mean 4.5
Standard Deviation:  2.8722813232690143
Median:  4.5


In [10]:
arr=np.array([[1,2,3],[4,5,7],[8,7,55]])
max_value=np.max(arr)
print("maximum Number: ",max_value)

min_value=np.min(arr)
print("Minimum Number: ",min_value)

maximum Number:  55
Minimum Number:  1


In [14]:
mean=0
standard_devi=1
R=np.random.normal(mean,standard_devi,1000)
print(R[5:])

[-3.98297294e-01  1.10458933e+00  1.74901124e+00  1.48498136e+00
 -2.57766295e-01  1.02121022e+00 -3.05979063e-01 -1.25131439e+00
 -8.46377771e-01  3.24300716e-01  6.22230574e-01  3.83838182e-01
 -1.02827577e+00  1.27236512e+00  5.96737320e-01 -1.87538930e-01
  9.86622039e-01 -1.38530409e+00 -4.00643372e-01 -5.17235026e-01
 -1.44162756e-01  1.57208577e+00 -9.80818580e-01  7.11247190e-01
 -2.63576849e-01  1.33055721e-01 -4.42301735e-01  1.16941386e-01
 -2.87076488e-01 -1.93763961e-01  4.23564033e-01  1.16843759e-01
  2.11371182e-01 -2.22715278e-01 -7.07475655e-01 -1.79971370e+00
  1.13970666e+00 -2.64059085e-01  2.42641437e-02 -2.00205928e+00
 -5.49274548e-01 -1.87611203e+00  9.39861524e-01  8.16423015e-02
 -1.05760348e+00  1.29134153e-01 -3.04960299e+00  2.60465904e-01
 -1.13896610e+00  8.44158444e-01 -3.44462346e+00 -5.94783353e-01
 -8.58174952e-01 -7.66103360e-02  4.73209091e-01  8.60180035e-01
  4.82632626e-01  4.55764657e-01  3.02971280e-01  2.25861153e-01
  5.78878189e-01  6.21603

In [15]:
low=10
high=50

array=np.random.uniform(low,high,size=(5,5))
print(array)

[[32.43145334 42.58215357 23.61576717 45.65150456 18.78450085]
 [49.01988191 41.81736249 29.87604561 36.62742178 14.45497308]
 [27.08647453 24.37984331 13.09676566 24.9961266  31.40492198]
 [27.02900679 26.05460629 18.35543374 49.40985938 40.73937718]
 [39.2788463  45.93955642 13.14330489 14.27761093 38.5429472 ]]


In [17]:
low1=10
high2=50

array3=np.random.randint(low1,high2,size=(5,5))
print(array3)

[[16 43 48 10 32]
 [17 25 12 24 11]
 [24 45 45 30 35]
 [17 29 18 49 21]
 [20 49 16 46 45]]


In [19]:
array=([1,5,2,4])
cum_sum=np.cumsum(array)
print(cum_sum)

[ 1  6  8 12]


In [20]:
array=([[1,5,2,4],[2,1,2,3]])
cum_sum=np.cumsum(array)
print(cum_sum)

[ 1  6  8 12 14 15 17 20]


In [22]:
array=([[[1,5,2,4],[2,1,2,3],[1,2,3,4]]])
cum_sum=np.cumsum(array)
print(cum_sum)

[ 1  6  8 12 14 15 17 20 21 23 26 30]


In [25]:
array2=([[1,3,2,1],[4,2,1,4]])
corr_matrix=np.corrcoef(array2)
print(corr_matrix)

[[ 1.         -0.75433651]
 [-0.75433651  1.        ]]


In [31]:
rolls=np.random.randint(1,7, size=1000)
unique,counts=np.unique(rolls,return_counts=True)
frequency=dict(zip(unique,counts))
print("frequencies: ")
print(frequency)

frequencies: 
{1: 189, 2: 168, 3: 168, 4: 164, 5: 156, 6: 155}
