In [1]:
import numpy as np


# Zero matirx

In [28]:
zero_matrix = np.zeros((3, 3)) 
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# identity_matrix

In [29]:
identity_matrix = np.eye(3)  
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# random_matrix

In [30]:
random_matrix = np.random.rand(3, 3)
random_matrix

array([[0.06813968, 0.23696607, 0.91067095],
       [0.81626169, 0.53214091, 0.74478815],
       [0.52640892, 0.80869188, 0.48235652]])

# Perform Basic Matrix Operations:

In [31]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
addition = A + B
subtraction = A - B
print('addition')
addition
print('subtraction')
subtraction

addition
subtraction


array([[-4, -4],
       [-4, -4]])

In [32]:
multiplication = np.dot(A, B)
print('multiplication')
multiplication

multiplication


array([[19, 22],
       [43, 50]])

In [33]:
transpose = A.T
print('Transpose of matrix')
transpose


Transpose of matrix


array([[1, 3],
       [2, 4]])

# Determinant and inverse

In [37]:
determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)

determinant

inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# System of Linear Equations:

In [40]:
A = np.array([[3, 2], [1, 2]])
b = np.array([5, 7])
x = np.linalg.solve(A, b)
A
b
x

array([-1.,  4.])

# LU Decompositiom

In [43]:
from scipy.linalg import lu
P, L, U = lu(A)
P,L,U

(array([[1., 0.],
        [0., 1.]]),
 array([[1.        , 0.        ],
        [0.33333333, 1.        ]]),
 array([[3.        , 2.        ],
        [0.        , 1.33333333]]))

# QR Decomposition

In [42]:
Q, R = np.linalg.qr(A)
Q,R

(array([[-0.9486833 , -0.31622777],
        [-0.31622777,  0.9486833 ]]),
 array([[-3.16227766, -2.52982213],
        [ 0.        ,  1.26491106]]))

# Eigenvalues and Eigenvectors

In [44]:
eigenvalues, eigenvectors = np.linalg.eig(A)
reconstructed_matrix = np.dot(eigenvectors, np.dot(np.diag(eigenvalues), np.linalg.inv(eigenvectors)))

eigenvalues, eigenvectors
reconstructed_matrix

array([[3., 2.],
       [1., 2.]])

# Vector operation

In [47]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
addition = v1 + v2

print('addition\n')
addition


addition



array([4, 6])

In [48]:
dot_product = np.dot(v1, v2)

print('dot_product\n')
dot_product


dot_product



11

In [49]:

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
cross_product = np.cross(v1, v2)
print('cross_product\n')
cross_product


cross_product



array([-3,  6, -3])

# normalize vetor 

In [53]:
norm = np.linalg.norm(v1)
normalized_v1 = v1 / norm
norm


3.7416573867739413

In [54]:
normalized_v1

array([0.26726124, 0.53452248, 0.80178373])

# vector norm

In [55]:
norm = np.linalg.norm(v1)
norm


3.7416573867739413

# Matrix Decomposition


In [56]:
#SvD
U, S, Vt = np.linalg.svd(A)
U, S, Vt

(array([[-0.86491009, -0.50192682],
        [-0.50192682,  0.86491009]]),
 array([4.13064859, 0.96837093]),
 array([[-0.74967818, -0.66180256],
        [-0.66180256,  0.74967818]]))

# Calculus Tasks

# Numerical Differentiation

In [58]:
def f(x):
    return x**2 + 3*x + 2


def forward_diff(f, x, h=1e-5):
    return (f(x + h) - f(x)) / h



def backward_diff(f, x, h=1e-5):
    return (f(x) - f(x - h)) / h

def central_diff(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)


x = 1.0
print("Forward Difference:", forward_diff(f, x))
print("Backward Difference:", backward_diff(f, x))
print("Central Difference:", central_diff(f, x))

Forward Difference: 5.0000099999891745
Backward Difference: 4.99998999998752
Central Difference: 4.999999999988347


# Numerical Integration:

In [61]:
def g(x):
    return np.sin(x)
#trapezoidal_rule
def trapezoidal_rule(f, a, b, n=1000):
    x = np.linspace(a, b, n)
    y = f(x)
    return np.trapz(y, x)

#simpsons_rule
from scipy.integrate import simps
def simpsons_rule(f, a, b, n=1000):
    x = np.linspace(a, b, n)
    y = f(x)
    return simps(y, x)


a, b = 0, np.pi
print("Trapezoidal Rule:", trapezoidal_rule(g, a, b))
print("Simpson's Rule:", simpsons_rule(g, a, b))


Trapezoidal Rule: 1.999998351770852
Simpson's Rule: 2.0000000000051616


C:\Users\PMYLS\AppData\Local\Temp\ipykernel_12544\2231965662.py:14: DeprecationWarning: 'scipy.integrate.simps' is deprecated in favour of 'scipy.integrate.simpson' and will be removed in SciPy 1.14.0
  return simps(y, x)


# Partial Derivatives:

In [25]:
from sympy import symbols, diff

x, y = symbols('x y')
f = x**2 + y**2
partial_x = diff(f, x)
partial_y = diff(f, y)
partial_x
partial_y

2*y

 # Optimization

In [59]:
from scipy.optimize import minimize

def objective(x):
    return x[0]**2 + x[1]**2

def constraint(x):
    return x[0] + x[1] - 1

constraints = {'type': 'eq', 'fun': constraint}
result = minimize(objective, [0, 0], constraints=constraints)

print("Optimization Result:")
print("  Success:", result.success)
print("  Optimal Value:", result.fun)
print("  Optimal Point:", result.x)


Optimization Result:
  Success: True
  Optimal Value: 0.5
  Optimal Point: [0.5 0.5]
