In [125]:
import numpy as np


In [126]:
#7
arr= np.arange(36).reshape(6,6)

In [127]:
print("Array")
print(arr)

Array
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [128]:
sub_arr=arr[1:3,1:3]

In [129]:
print("sub_array")
print(sub_arr)

sub_array
[[ 7  8]
 [13 14]]


In [130]:
#8
arr3=np.arange(6).reshape(3,2,1)
print("Original Array")
print(arr3)

extract_ele = arr3[1,:2, :]
print("\nextract elements of array")
print(extract_ele)



Original Array
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]]

extract elements of array
[[2]
 [3]]


In [131]:
#9
arr5= np.array([12,3,4,5,6,7,4,3])
print(arr5)
position=[1,3,4,6]

ele=arr5[position]
print(ele)

[12  3  4  5  6  7  4  3]
[3 5 6 4]


In [132]:
#10 i have used fancy indexing here ,this comment is just for reminder ,for myself
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("array")
print(x)
row=[0,2,2]
col=[1,3]

ans=x[row, :][:, col]
print("Extracted elements")
print(ans)

array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Extracted elements
[[ 2  4]
 [10 12]
 [10 12]]


In [133]:
# just for practise fancy indexing ,its not task.
x=np.arange(36).reshape(6,6)
print("array ")
print(x)

row=np.array([1,2,3])
col= np.array([2,1,3])
x[row,col]


array 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([ 8, 13, 21])

In [134]:
#11
arr=np.array([12,13,2,3,5,16,8,7,1,10])
print("Array:")
print(arr)
bolean_mask=arr>8
elements= arr[bolean_mask]
print("Extracted elements that are greater then 8")
print(elements)

Array:
[12 13  2  3  5 16  8  7  1 10]
Extracted elements that are greater then 8
[12 13 16 10]


In [135]:
#12
arr=np.arange(36).reshape(6,6)
print("Array:")
print(arr)
bolean_mask=arr>13
arr[bolean_mask]=0
print("Replaced: \n")
print(arr)



Array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Replaced: 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


In [136]:
# 5 broadcasting
array1D=np.array([1,2,3])
array2D=np.array([[10,20,30],[40,50,60],[40,10,20],[30,40,50]])
result=np.add(array1D,array2D)
print(array1D)
print(array2D)
print("result")
print(result)

[1 2 3]
[[10 20 30]
 [40 50 60]
 [40 10 20]
 [30 40 50]]
result
[[11 22 33]
 [41 52 63]
 [41 12 23]
 [31 42 53]]


In [137]:
#6
x=np.array([[1,2,3],[2,3,4],[4,3,2]])
print(x.shape)
y=np.array([1,2,3])
print(y.shape)
z=x*y
print(z)

(3, 3)
(3,)
[[ 1  4  9]
 [ 2  6 12]
 [ 4  6  6]]


In [138]:
# further practise of broadcasting
c=np.array([1,2])
print(c)
d=np.array([[1],[3]])
print(d)
f=c*d
print("product")
print(f)

[1 2]
[[1]
 [3]]
product
[[1 2]
 [3 6]]


In [139]:
#7
s=np.array([[1],[2],[4]])
print(s.shape)
r=np.array([[1,2,3,4]])
print(r.shape)

print("array1\n",s)
print("array2\n",r)

ans=np.add(s,r)
print("sum")
print(ans)

(3, 1)
(1, 4)
array1
 [[1]
 [2]
 [4]]
array2
 [[1 2 3 4]]
sum
[[2 3 4 5]
 [3 4 5 6]
 [5 6 7 8]]


In [140]:
#8
g = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])
print(g.shape)
h=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(h.shape)

print("array1\n",s)
print("array2\n",r)

ans= g+h
print("sum")
print(ans)

(2, 3, 4)
(3, 4)
array1
 [[1]
 [2]
 [4]]
array2
 [[1 2 3 4]]
sum
[[[ 2  4  6  8]
  [ 6  8 10 12]
  [10 12 14 16]]

 [[14 16 18 20]
  [18 20 22 24]
  [22 24 26 28]]]


In [141]:
#some more 7
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("array 2D")
print(arr1)
s=arr1[::2,::2]
print("Sliced array")
print(s)
arr2=([1,2,3])
print("array 1D")
print(arr2)
added=arr2 + s
print("sum of arrays:")
print(added)

array 2D
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sliced array
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
array 1D
[1, 2, 3]
sum of arrays:
[[ 2  5  8]
 [12 15 18]
 [22 25 28]]


In [142]:
#8
a=np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print("3d array")
print(a)

sub=a[:,:,:]
print("sub_array")
print(sub)

b=np.array([[1,2],[1,2],[2,3]])
print("2d array")
print(b)

extract= b[:, :,np.newaxis]
answer= sub - extract
print("answer")
print(answer)

3d array
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
sub_array
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
2d array
[[1 2]
 [1 2]
 [2 3]]
answer
[[[0]
  [0]]

 [[2]
  [2]]

 [[3]
  [3]]]


In [143]:
#9
arr=np.array([[1,2,3],[2,3,4],[2,3,4]])
dia_ele=np.diag(arr)
print("diagonal elements",dia_ele)

array_1d_dia=dia_ele.flatten()
print("diagonal elements as 1D array",array_1d_dia)

diagonal elements [1 3 4]
diagonal elements as 1D array [1 3 4]


In [144]:
#10
arr=np.array([[1,2,3],[2,3,4],[2,3,4]])
reversed_arr=arr[:,::-1]
print("origiinal array")
print(arr)

print("reversed array")
print(reversed_arr)


origiinal array
[[1 2 3]
 [2 3 4]
 [2 3 4]]
reversed array
[[3 2 1]
 [4 3 2]
 [4 3 2]]


In [145]:
#11
arr3D=np.random.randint(0,10,size=(7,6,5))
sub_arr=arr3D[:2, :3, :4]
arr1D=np.array([1,2,3,4])
result=sub_arr+ arr1D

print("3D array shape",arr3D.shape)
print("sub array shape",sub_arr.shape) 
print("1D array sshape",arr1D.shape)
print("result array shape",result.shape)
print("sub array")
print(sub_arr)
print("1D array")
print(arr1D)

print("result")
print(result)

3D array shape (7, 6, 5)
sub array shape (2, 3, 4)
1D array sshape (4,)
result array shape (2, 3, 4)
sub array
[[[5 7 9 3]
  [3 3 3 9]
  [0 0 6 1]]

 [[3 7 4 6]
  [0 5 8 3]
  [2 8 4 6]]]
1D array
[1 2 3 4]
result
[[[ 6  9 12  7]
  [ 4  5  6 13]
  [ 1  2  9  5]]

 [[ 4  9  7 10]
  [ 1  7 11  7]
  [ 3 10  7 10]]]


In [146]:
#12
arr=np.random.randint(1,10,size=(5,3))
print("array")
print(arr)

arr[:,-1]= arr[:,0] + arr[:,1]
print("colomun adition")
print(arr)

array
[[2 8 2]
 [1 8 6]
 [4 8 4]
 [6 6 8]
 [5 8 1]]
colomun adition
[[ 2  8 10]
 [ 1  8  9]
 [ 4  8 12]
 [ 6  6 12]
 [ 5  8 13]]
